name: agriplant
description: Agriculture plant app
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^5.1.0
  badges: ^3.1.1
  timelines: ^0.1.0
  easy_stepper: ^0.7.3
  smooth_page_indicator: ^1.2.0+3



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/services/
    - assets/login/
    - assets/banner/
    - assets/banner/rau1.jpg
    - assets/banner/rau2.png
    - assets/banner/rau3.jpg
    - assets/banner/rau4.jpg
    - shorebird.yaml
